version: "3.7"
services:
  app:
    build:
      args:
        user: Vladr
        uid: 1000
      context: ./backend/
      dockerfile: Dockerfile
    image: pickmanager
    container_name: pickmanager-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend/:/var/www
    networks:
      - pickmanager
  db:
    image: mysql:5.7
    container_name: pickmanager-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - pickmanager

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
    ports:
      - 8081:80
    networks:
      - pickmanager
  nginx:
    image: nginx:1.17-alpine
    container_name: pickmanager-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./backend/:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - pickmanager

networks:
  pickmanager:
    driver: bridge